language: php
php:
- '5.5'
script: echo "We don't have tests yet :("
before_deploy:
- sh config.sh
- sh package.sh
deploy:
  provider: releases
  name: "$TRAVIS_TAG"
  api_key:
    secure: Z2FYa4Z1dATLvPXjTtSR66y+g7OWsxA4Z3nb9zI/H2ce6Huei2bbfY0aosP0I2O2+p7ncxjbVA/nby7mqdg9OGfSNv4wNX2hwtLogbU0Iz0O/7jtcXjPtn3ZRsOw2O/P4fd2V6uEjWeeOO7K3EZy4QgYZPAorgFQPr8bhPkotqzyQhmKhpW82CWQpFFnhs9VsFhgb+IiKZ+NYwZs2Ba3ufHSt9ccK+gg6ymIlVLqGBaQRqyDXxthcGAAb4CGbQVYgUfCZIed1QHg+l89z9+ETeGnkGV9WgaGaWghLNMeUGG8qIt8UXbu+XNv0wMoQYEtsjQ9fevKHSEAVwxYp/kt3cS3RzW9viCwypKyg7Y+NkzzSqQTHsggLF4XLg0iTROLqYQdSp6amtiafiGuhN7q+9P91YplrEAF5TKSLAUwmsywX60MCPo60wV+4jAvAES5LsQpikrilF95PSuXGMyoOwuKBml7XPpezetsTh0VHmoYBD8ve2eHG09S6jOGFSAB2PtDZeIcVyPuCQl2Ronuc/RqaD1R0zF7vc2lv5iPMOdDa8tYdWHdhSjQ4SiEOCZHqTA236yHW2eF/4eAiQrJvClZprGxFe5ZfBj8Cx37K6mFWDijscHpSBucgQJEIq1F6/MOReIyP3q+AvjTOAD/zqIu7Ke78Yqi8hTcm0kaAf8=
  file: plugin-transbank-webpay-opencart3-$TRAVIS_TAG.ocmod.zip
  skip_cleanup: true
  on:
    repo: TransbankDevelopers/transbank-plugin-opencart-webpay
    tags: true
